// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: auther/api/grpc/auther.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JWTToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *JWTToken) Reset() {
	*x = JWTToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auther_api_grpc_auther_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTToken) ProtoMessage() {}

func (x *JWTToken) ProtoReflect() protoreflect.Message {
	mi := &file_auther_api_grpc_auther_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTToken.ProtoReflect.Descriptor instead.
func (*JWTToken) Descriptor() ([]byte, []int) {
	return file_auther_api_grpc_auther_proto_rawDescGZIP(), []int{0}
}

func (x *JWTToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JWTClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid  bool                   `protobuf:"varint,1,opt,name=Valid,proto3" json:"Valid,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email  string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Expiry *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *JWTClaims) Reset() {
	*x = JWTClaims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auther_api_grpc_auther_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTClaims) ProtoMessage() {}

func (x *JWTClaims) ProtoReflect() protoreflect.Message {
	mi := &file_auther_api_grpc_auther_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTClaims.ProtoReflect.Descriptor instead.
func (*JWTClaims) Descriptor() ([]byte, []int) {
	return file_auther_api_grpc_auther_proto_rawDescGZIP(), []int{1}
}

func (x *JWTClaims) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *JWTClaims) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JWTClaims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JWTClaims) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

var File_auther_api_grpc_auther_proto protoreflect.FileDescriptor

var file_auther_api_grpc_auther_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x75, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x4a, 0x57, 0x54, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7f, 0x0a, 0x09, 0x4a, 0x57, 0x54,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x32, 0x3c, 0x0a, 0x06, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x4a, 0x57, 0x54, 0x12, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4a, 0x57, 0x54,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x4a,
	0x57, 0x54, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_auther_api_grpc_auther_proto_rawDescOnce sync.Once
	file_auther_api_grpc_auther_proto_rawDescData = file_auther_api_grpc_auther_proto_rawDesc
)

func file_auther_api_grpc_auther_proto_rawDescGZIP() []byte {
	file_auther_api_grpc_auther_proto_rawDescOnce.Do(func() {
		file_auther_api_grpc_auther_proto_rawDescData = protoimpl.X.CompressGZIP(file_auther_api_grpc_auther_proto_rawDescData)
	})
	return file_auther_api_grpc_auther_proto_rawDescData
}

var file_auther_api_grpc_auther_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auther_api_grpc_auther_proto_goTypes = []interface{}{
	(*JWTToken)(nil),              // 0: auther.JWTToken
	(*JWTClaims)(nil),             // 1: auther.JWTClaims
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_auther_api_grpc_auther_proto_depIdxs = []int32{
	2, // 0: auther.JWTClaims.expiry:type_name -> google.protobuf.Timestamp
	0, // 1: auther.Auther.ValidateJWT:input_type -> auther.JWTToken
	1, // 2: auther.Auther.ValidateJWT:output_type -> auther.JWTClaims
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auther_api_grpc_auther_proto_init() }
func file_auther_api_grpc_auther_proto_init() {
	if File_auther_api_grpc_auther_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auther_api_grpc_auther_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWTToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auther_api_grpc_auther_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWTClaims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auther_api_grpc_auther_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auther_api_grpc_auther_proto_goTypes,
		DependencyIndexes: file_auther_api_grpc_auther_proto_depIdxs,
		MessageInfos:      file_auther_api_grpc_auther_proto_msgTypes,
	}.Build()
	File_auther_api_grpc_auther_proto = out.File
	file_auther_api_grpc_auther_proto_rawDesc = nil
	file_auther_api_grpc_auther_proto_goTypes = nil
	file_auther_api_grpc_auther_proto_depIdxs = nil
}
