version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    #ports:
    #  - 22181:2181
    networks:
      - kafka
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    #ports:
    #  - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka
      - application

  spinupper:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    networks:
      - kafka
    command:
      - sh
      - -c
      -| 
        kafka-topics --create --topic rooms_chat --bootstrap-server PLAINTEXT://kafka:9092 &&
        kafka-topics --create --topic social_events --bootstrap-server PLAINTEXT://kafka:9092 && # Subscriptions, chat messages, etc
        kafka-topics --create --topic events --bootstrap-server PLAINTEXT://kafka:9092 # Room creation, etc
    # Numero di partizioni? - per i consumer group


  auther:
    build: auther/
    enviroment:
      JWT_SECRET: I like trains
      DB: bow
    
networks:
  kafka:
  application: